import { NextRequest, NextResponse } from 'next/server'

export async function GET(request: NextRequest) {
  const searchParams = request.nextUrl.searchParams
  const destination = searchParams.get('destination')

  // Mock product data with images and detailed info
  const products = [
    {
      id: 1,
      title: 'MacSafe - Laptop Protection',
      description: 'Premium laptop sleeve with magnetic closure for MacBook',
      category: 'Electronics',
      price: 29.99,
      currency: 'USD',
      rating: 4.7,
      reviews: 1543,
      image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=400&h=400&fit=crop',
      affiliateUrl: 'https://amzn.in/d/duI0CYb',
      features: ['Magnetic closure', 'Soft interior', 'Slim design'],
    },
    {
      id: 2,
      title: 'High-Capacity Power Bank',
      description: '20000mAh portable charger with fast charging technology',
      category: 'Electronics',
      price: 34.99,
      currency: 'USD',
      rating: 4.8,
      reviews: 2341,
      image: 'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=400&h=400&fit=crop',
      affiliateUrl: 'https://amzn.in/d/aCG7Dks',
      features: ['Fast charging', 'LED indicator', 'Dual USB ports'],
    },
    {
      id: 3,
      title: 'Premium Leather Jacket',
      description: 'Stylish genuine leather jacket for all-season travel',
      category: 'Clothing',
      price: 149.99,
      currency: 'USD',
      rating: 4.6,
      reviews: 876,
      image: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=400&h=400&fit=crop',
      affiliateUrl: 'https://amzn.in/d/8QwT5hJ',
      features: ['Genuine leather', 'Multiple pockets', 'Classic style'],
    },
    {
      id: 4,
      title: 'Travel Backpack - Large Capacity',
      description: 'Spacious travel bag with multiple compartments and USB port',
      category: 'Luggage',
      price: 59.99,
      currency: 'USD',
      rating: 4.7,
      reviews: 1987,
      image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&h=400&fit=crop',
      affiliateUrl: 'https://amzn.in/d/3cLZLUS',
      features: ['USB charging port', 'Water-resistant', 'Laptop compartment'],
    },
    {
      id: 5,
      title: 'Rolling Suitcase - Hard Shell',
      description: 'Durable hard-shell suitcase with smooth rolling wheels',
      category: 'Luggage',
      price: 89.99,
      currency: 'USD',
      rating: 4.5,
      reviews: 1234,
      image: 'https://images.unsplash.com/photo-1565026057447-bc90a3dceb87?w=400&h=400&fit=crop',
      affiliateUrl: 'https://amzn.in/d/brpE8hw',
      features: ['TSA lock', '360° wheels', 'Lightweight'],
    },
    {
      id: 6,
      title: 'Noise-Cancelling Headphones',
      description: 'Premium over-ear headphones with active noise cancellation',
      category: 'Electronics',
      price: 129.99,
      currency: 'USD',
      rating: 4.9,
      reviews: 3210,
      image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=400&fit=crop',
      affiliateUrl: 'https://amzn.in/d/bfHnyeu',
      features: ['Active noise cancelling', '30hr battery', 'Foldable'],
    },
    {
      id: 7,
      title: 'AirPods 4 - Wireless Earbuds',
      description: 'Latest generation AirPods with improved sound quality',
      category: 'Electronics',
      price: 179.99,
      currency: 'USD',
      rating: 4.8,
      reviews: 5432,
      image: 'https://images.unsplash.com/photo-1606841837239-c5a1a4a07af7?w=400&h=400&fit=crop',
      affiliateUrl: 'https://amzn.in/d/isai1sQ',
      features: ['Spatial audio', 'Long battery', 'Quick charging'],
    },
    {
      id: 8,
      title: 'Insulated Water Bottle',
      description: 'Stainless steel vacuum bottle keeps drinks cold/hot for 24hrs',
      category: 'Essentials',
      price: 24.99,
      currency: 'USD',
      rating: 4.7,
      reviews: 1876,
      image: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=400&h=400&fit=crop',
      affiliateUrl: 'https://amzn.in/d/0LgsBSS',
      features: ['24hr insulation', 'Leak-proof', 'BPA-free'],
    },
    {
      id: 9,
      title: 'Funky Fashion Glasses',
      description: 'Trendy eyewear with unique frame design',
      category: 'Accessories',
      price: 19.99,
      currency: 'USD',
      rating: 4.4,
      reviews: 654,
      image: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=400&h=400&fit=crop',
      affiliateUrl: 'https://amzn.in/d/j9hhiK7',
      features: ['UV protection', 'Lightweight', 'Stylish design'],
    },
    {
      id: 10,
      title: 'Sunglasses for Men',
      description: 'Classic aviator sunglasses with polarized lenses',
      category: 'Accessories',
      price: 29.99,
      currency: 'USD',
      rating: 4.6,
      reviews: 2109,
      image: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=400&h=400&fit=crop',
      affiliateUrl: 'https://amzn.in/d/cWyX7fs',
      features: ['Polarized lenses', 'UV400 protection', 'Metal frame'],
    },
    {
      id: 11,
      title: 'Sunglasses for Women',
      description: 'Elegant cat-eye sunglasses with gradient lenses',
      category: 'Accessories',
      price: 27.99,
      currency: 'USD',
      rating: 4.7,
      reviews: 1543,
      image: 'https://images.unsplash.com/photo-1508296695146-257a814070b4?w=400&h=400&fit=crop',
      affiliateUrl: 'https://amzn.in/d/gn4tF1O',
      features: ['Cat-eye design', 'UV protection', 'Gradient lenses'],
    },
    {
      id: 12,
      title: 'Women\'s Travel Cap',
      description: 'Stylish baseball cap with adjustable strap',
      category: 'Accessories',
      price: 14.99,
      currency: 'USD',
      rating: 4.5,
      reviews: 987,
      image: 'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=400&h=400&fit=crop',
      affiliateUrl: 'https://amzn.in/d/ehQnmrN',
      features: ['Adjustable fit', 'Breathable fabric', 'Sun protection'],
    },
  ]

  return NextResponse.json({
    destination,
    products,
    totalProducts: products.length,
  })
}
